// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/wireinject/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wireit

import (
	"github.com/domesama/chat-and-notifications/chatpersistence/handler"
	"github.com/domesama/chat-and-notifications/chatpersistence/service"
	"github.com/domesama/chat-and-notifications/cmd/chatpersistence/wire"
	"github.com/domesama/chat-and-notifications/connections"
	"github.com/domesama/chat-and-notifications/connections/connectionconfig"
	"github.com/domesama/chat-and-notifications/httpserverwrapper"
	"github.com/domesama/doakes/doakeswire"
)

// Injectors from di.go:

func InitChatPersistenceITTestContainer() (ChatPersistenceITTestContainer, func(), error) {
	mongoDBConfig := connectionconfig.ProvideMongoDBConfig()
	client, cleanup, err := connections.ProvideMongoClient(mongoDBConfig)
	if err != nil {
		return ChatPersistenceITTestContainer{}, nil, err
	}
	database := connections.ProvideMongoDatabase(client, mongoDBConfig)
	chatPersistenceService := service.ChatPersistenceService{
		DB: database,
	}
	chatPersistenceHandler := &handler.ChatPersistenceHandler{
		ChatPersistenceService: chatPersistenceService,
	}
	handlerChatPersistenceHandler := handler.ChatPersistenceHandler{
		ChatPersistenceService: chatPersistenceService,
	}
	routerCustomizer := handler.ProvideRouterCustomizer(handlerChatPersistenceHandler)
	serviceChatPersistenceService := &service.ChatPersistenceService{
		DB: database,
	}
	locator := wire.Locator{
		ChatPersistenceHandler: chatPersistenceHandler,
		RouterCustomizer:       routerCustomizer,
		ChatPersistenceService: serviceChatPersistenceService,
	}
	resource, err := doakeswire.ProvideResource()
	if err != nil {
		cleanup()
		return ChatPersistenceITTestContainer{}, nil, err
	}
	metricsConfig := doakeswire.ProvideMetricsConfig()
	telemetryServerConfig, err := doakeswire.ProvideTelemetryServerConfig()
	if err != nil {
		cleanup()
		return ChatPersistenceITTestContainer{}, nil, err
	}
	options := doakeswire.ProvideServerOptions(resource, metricsConfig, telemetryServerConfig)
	telemetryServer, cleanup2, err := doakeswire.ProvideServer(options)
	if err != nil {
		cleanup()
		return ChatPersistenceITTestContainer{}, nil, err
	}
	httpServerConfig := httpserverwrapper.ProvideHTTPConfig()
	httpServer, cleanup3, err := httpserverwrapper.ProvideHTTPServer(httpServerConfig, routerCustomizer)
	if err != nil {
		cleanup2()
		cleanup()
		return ChatPersistenceITTestContainer{}, nil, err
	}
	chatPersistenceContainer := wire.ChatPersistenceContainer{
		TelemetryServer: telemetryServer,
		HTTPServer:      httpServer,
	}
	chatPersistenceITTestContainer := ChatPersistenceITTestContainer{
		Locator:                  locator,
		ChatPersistenceContainer: chatPersistenceContainer,
		Database:                 database,
	}
	return chatPersistenceITTestContainer, func() {
		cleanup3()
		cleanup2()
		cleanup()
	}, nil
}
