// Code generated by wireprovider version v1.0.2. DO NOT EDIT.

package wire

import (
	"github.com/google/wire"

	jwvkhhandler "github.com/domesama/chat-and-notifications/chatpersistence/handler"
	jwvkhservice "github.com/domesama/chat-and-notifications/chatpersistence/service"
	hyhnghttpserverwrapper "github.com/domesama/chat-and-notifications/httpserverwrapper"
)

var ProviderSet = wire.NewSet(
	wire.Struct(new(jwvkhhandler.ChatPersistenceHandler), "*"),
	jwvkhhandler.ProvideRouterCustomizer,
	wire.Struct(new(jwvkhservice.ChatPersistenceService), "*"),
)

type Locator struct {
	ChatPersistenceHandler *jwvkhhandler.ChatPersistenceHandler
	RouterCustomizer       hyhnghttpserverwrapper.RouterCustomizer
	ChatPersistenceService *jwvkhservice.ChatPersistenceService
}
