// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/wireinject/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wire

import (
	"github.com/domesama/chat-and-notifications/chatpersistence/handler"
	"github.com/domesama/chat-and-notifications/chatpersistence/service"
	"github.com/domesama/chat-and-notifications/connections"
	"github.com/domesama/chat-and-notifications/connections/connectionconfig"
	"github.com/domesama/chat-and-notifications/httpserverwrapper"
	"github.com/domesama/doakes/doakeswire"
)

// Injectors from chat_persistence_di.go:

func StartChatPersistenceContainer() (ChatPersistenceContainer, func(), error) {
	resource, err := doakeswire.ProvideResource()
	if err != nil {
		return ChatPersistenceContainer{}, nil, err
	}
	metricsConfig := doakeswire.ProvideMetricsConfig()
	telemetryServerConfig, err := doakeswire.ProvideTelemetryServerConfig()
	if err != nil {
		return ChatPersistenceContainer{}, nil, err
	}
	options := doakeswire.ProvideServerOptions(resource, metricsConfig, telemetryServerConfig)
	telemetryServer, cleanup, err := doakeswire.ProvideServer(options)
	if err != nil {
		return ChatPersistenceContainer{}, nil, err
	}
	httpServerConfig := httpserverwrapper.ProvideHTTPConfig()
	mongoDBConfig := connectionconfig.ProvideMongoDBConfig()
	client, cleanup2, err := connections.ProvideMongoClient(mongoDBConfig)
	if err != nil {
		cleanup()
		return ChatPersistenceContainer{}, nil, err
	}
	database := connections.ProvideMongoDatabase(client, mongoDBConfig)
	chatPersistenceService := service.ChatPersistenceService{
		DB: database,
	}
	chatPersistenceHandler := handler.ChatPersistenceHandler{
		ChatPersistenceService: chatPersistenceService,
	}
	routerCustomizer := handler.ProvideRouterCustomizer(chatPersistenceHandler)
	httpServer, cleanup3, err := httpserverwrapper.ProvideHTTPServer(httpServerConfig, routerCustomizer)
	if err != nil {
		cleanup2()
		cleanup()
		return ChatPersistenceContainer{}, nil, err
	}
	chatPersistenceContainer := ChatPersistenceContainer{
		TelemetryServer: telemetryServer,
		HTTPServer:      httpServer,
	}
	return chatPersistenceContainer, func() {
		cleanup3()
		cleanup2()
		cleanup()
	}, nil
}
