// Code generated by wireprovider version v1.0.2. DO NOT EDIT.

package wire

import (
	"github.com/google/wire"

	cxiyrhandler "github.com/domesama/chat-and-notifications/generalnotifications/handler"
	hyhnghttpserverwrapper "github.com/domesama/chat-and-notifications/httpserverwrapper"
)

var ProviderSet = wire.NewSet(
	wire.Struct(new(cxiyrhandler.GeneralNotificationWebSocketHandler), "*"),
	cxiyrhandler.ProvideRouterCustomizer,
)

type Locator struct {
	GeneralNotificationWebSocketHandler *cxiyrhandler.GeneralNotificationWebSocketHandler
	RouterCustomizer                    hyhnghttpserverwrapper.RouterWithWebSocketCustomizer
}
