// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/wireinject/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wire

import (
	"github.com/domesama/chat-and-notifications/generalnotifications/handler"
	"github.com/domesama/chat-and-notifications/httpserverwrapper"
	"github.com/domesama/chat-and-notifications/websocket"
	"github.com/domesama/doakes/doakeswire"
)

// Injectors from general_notification_di.go:

func StartGeneralNotificationHandlerContainer() (GeneralNotificationHandlerContainer, func(), error) {
	httpServerConfig := httpserverwrapper.ProvideHTTPConfig()
	webSocketConfig := websocket.ProvideWebSocketConfig()
	webSocketManager := websocket.ProvideDefaultWebSocketManager(webSocketConfig)
	generalNotificationWebSocketHandler := handler.GeneralNotificationWebSocketHandler{
		WebSocketManager: webSocketManager,
	}
	routerWithWebSocketCustomizer := handler.ProvideRouterCustomizer(generalNotificationWebSocketHandler)
	httpWithWebSocketServer, cleanup, err := httpserverwrapper.ProvideHTTPWithWebSocketServer(httpServerConfig, routerWithWebSocketCustomizer, webSocketManager)
	if err != nil {
		return GeneralNotificationHandlerContainer{}, nil, err
	}
	resource, err := doakeswire.ProvideResource()
	if err != nil {
		cleanup()
		return GeneralNotificationHandlerContainer{}, nil, err
	}
	metricsConfig := doakeswire.ProvideMetricsConfig()
	telemetryServerConfig, err := doakeswire.ProvideTelemetryServerConfig()
	if err != nil {
		cleanup()
		return GeneralNotificationHandlerContainer{}, nil, err
	}
	options := doakeswire.ProvideServerOptions(resource, metricsConfig, telemetryServerConfig)
	telemetryServer, cleanup2, err := doakeswire.ProvideServer(options)
	if err != nil {
		cleanup()
		return GeneralNotificationHandlerContainer{}, nil, err
	}
	generalNotificationHandlerContainer := GeneralNotificationHandlerContainer{
		HTTPWithWebSocketServer: httpWithWebSocketServer,
		TelemetryServer:         telemetryServer,
	}
	return generalNotificationHandlerContainer, func() {
		cleanup2()
		cleanup()
	}, nil
}
