// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/wireinject/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wireit

import (
	"github.com/domesama/chat-and-notifications/chatwebsocketshandler/handler"
	"github.com/domesama/chat-and-notifications/chatwebsocketshandler/service"
	"github.com/domesama/chat-and-notifications/cmd/chatwebsocketshandler/wire"
	"github.com/domesama/chat-and-notifications/connections"
	"github.com/domesama/chat-and-notifications/connections/connectionconfig"
	"github.com/domesama/chat-and-notifications/httpserverwrapper"
	"github.com/domesama/chat-and-notifications/websocket"
	"github.com/domesama/doakes/doakeswire"
)

// Injectors from di.go:

func InitChatWebSocketHandlerITTestContainer() (ChatWebSocketHandlerITTestContainer, func(), error) {
	webSocketConfig := websocket.ProvideWebSocketConfig()
	webSocketManager := websocket.ProvideDefaultWebSocketManager(webSocketConfig)
	chatWebSocketHandler := &handler.ChatWebSocketHandler{
		WebSocketManager: webSocketManager,
	}
	handlerChatWebSocketHandler := handler.ChatWebSocketHandler{
		WebSocketManager: webSocketManager,
	}
	routerWithWebSocketCustomizer := handler.ProvideRouterCustomizer(handlerChatWebSocketHandler)
	mongoDBConfig := connectionconfig.ProvideMongoDBConfig()
	client, cleanup, err := connections.ProvideMongoClient(mongoDBConfig)
	if err != nil {
		return ChatWebSocketHandlerITTestContainer{}, nil, err
	}
	database := connections.ProvideMongoDatabase(client, mongoDBConfig)
	chatPersistenceService := &service.ChatPersistenceService{
		DB: database,
	}
	locator := wire.Locator{
		ChatWebSocketHandler:   chatWebSocketHandler,
		RouterCustomizer:       routerWithWebSocketCustomizer,
		ChatPersistenceService: chatPersistenceService,
	}
	httpServerConfig := httpserverwrapper.ProvideHTTPConfig()
	httpWithWebSocketServer, cleanup2, err := httpserverwrapper.ProvideHTTPWithWebSocketServer(httpServerConfig, routerWithWebSocketCustomizer, webSocketManager)
	if err != nil {
		cleanup()
		return ChatWebSocketHandlerITTestContainer{}, nil, err
	}
	resource, err := doakeswire.ProvideResource()
	if err != nil {
		cleanup2()
		cleanup()
		return ChatWebSocketHandlerITTestContainer{}, nil, err
	}
	metricsConfig := doakeswire.ProvideMetricsConfig()
	telemetryServerConfig, err := doakeswire.ProvideTelemetryServerConfig()
	if err != nil {
		cleanup2()
		cleanup()
		return ChatWebSocketHandlerITTestContainer{}, nil, err
	}
	options := doakeswire.ProvideServerOptions(resource, metricsConfig, telemetryServerConfig)
	telemetryServer, cleanup3, err := doakeswire.ProvideServer(options)
	if err != nil {
		cleanup2()
		cleanup()
		return ChatWebSocketHandlerITTestContainer{}, nil, err
	}
	chatWebSocketHandlerContainer := wire.ChatWebSocketHandlerContainer{
		HTTPWithWebSocketServer: httpWithWebSocketServer,
		TelemetryServer:         telemetryServer,
	}
	chatWebSocketHandlerITTestContainer := ChatWebSocketHandlerITTestContainer{
		Locator:                       locator,
		ChatWebSocketHandlerContainer: chatWebSocketHandlerContainer,
	}
	return chatWebSocketHandlerITTestContainer, func() {
		cleanup3()
		cleanup2()
		cleanup()
	}, nil
}
