// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/wireinject/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wireit

import (
	"github.com/domesama/chat-and-notifications/cmd/generalnotificationshandler/wire"
	"github.com/domesama/chat-and-notifications/generalnotifications/handler"
	"github.com/domesama/chat-and-notifications/httpserverwrapper"
	"github.com/domesama/chat-and-notifications/websocket"
	"github.com/domesama/doakes/doakeswire"
)

// Injectors from di.go:

func InitGeneralNotificationHandlerITTestContainer() (GeneralNotificationHandlerITTestContainer, func(), error) {
	webSocketConfig := websocket.ProvideWebSocketConfig()
	webSocketManager := websocket.ProvideDefaultWebSocketManager(webSocketConfig)
	generalNotificationWebSocketHandler := &handler.GeneralNotificationWebSocketHandler{
		WebSocketManager: webSocketManager,
	}
	handlerGeneralNotificationWebSocketHandler := handler.GeneralNotificationWebSocketHandler{
		WebSocketManager: webSocketManager,
	}
	routerWithWebSocketCustomizer := handler.ProvideRouterCustomizer(handlerGeneralNotificationWebSocketHandler)
	locator := wire.Locator{
		GeneralNotificationWebSocketHandler: generalNotificationWebSocketHandler,
		RouterCustomizer:                    routerWithWebSocketCustomizer,
	}
	httpServerConfig := httpserverwrapper.ProvideHTTPConfig()
	httpWithWebSocketServer, cleanup, err := httpserverwrapper.ProvideHTTPWithWebSocketServer(httpServerConfig, routerWithWebSocketCustomizer, webSocketManager)
	if err != nil {
		return GeneralNotificationHandlerITTestContainer{}, nil, err
	}
	resource, err := doakeswire.ProvideResource()
	if err != nil {
		cleanup()
		return GeneralNotificationHandlerITTestContainer{}, nil, err
	}
	metricsConfig := doakeswire.ProvideMetricsConfig()
	telemetryServerConfig, err := doakeswire.ProvideTelemetryServerConfig()
	if err != nil {
		cleanup()
		return GeneralNotificationHandlerITTestContainer{}, nil, err
	}
	options := doakeswire.ProvideServerOptions(resource, metricsConfig, telemetryServerConfig)
	telemetryServer, cleanup2, err := doakeswire.ProvideServer(options)
	if err != nil {
		cleanup()
		return GeneralNotificationHandlerITTestContainer{}, nil, err
	}
	generalNotificationHandlerContainer := wire.GeneralNotificationHandlerContainer{
		HTTPWithWebSocketServer: httpWithWebSocketServer,
		TelemetryServer:         telemetryServer,
	}
	generalNotificationHandlerITTestContainer := GeneralNotificationHandlerITTestContainer{
		Locator:                             locator,
		GeneralNotificationHandlerContainer: generalNotificationHandlerContainer,
	}
	return generalNotificationHandlerITTestContainer, func() {
		cleanup2()
		cleanup()
	}, nil
}
