// Code generated by wireprovider version v1.0.2. DO NOT EDIT.

package wire

import (
	"github.com/google/wire"

	cfngjhandler "github.com/domesama/chat-and-notifications/emailhandler/handler"
	cfngjservice "github.com/domesama/chat-and-notifications/emailhandler/service"
	hyhnghttpserverwrapper "github.com/domesama/chat-and-notifications/httpserverwrapper"
)

var ProviderSet = wire.NewSet(
	wire.Struct(new(cfngjhandler.EmailHandler), "*"),
	cfngjhandler.ProvideRouterCustomizer,
	wire.Struct(new(cfngjservice.ChatMailingService), "*"),
	wire.Struct(new(cfngjservice.EmailInfoService), "*"),
	wire.Struct(new(cfngjservice.PurchaseMailingService), "*"),
)

type Locator struct {
	EmailHandler           *cfngjhandler.EmailHandler
	RouterCustomizer       hyhnghttpserverwrapper.RouterCustomizer
	ChatMailingService     *cfngjservice.ChatMailingService
	EmailInfoService       *cfngjservice.EmailInfoService
	PurchaseMailingService *cfngjservice.PurchaseMailingService
}
