// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/wireinject/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wire

import (
	"github.com/domesama/chat-and-notifications/connections"
	"github.com/domesama/chat-and-notifications/connections/connectionconfig"
	"github.com/domesama/chat-and-notifications/email"
	"github.com/domesama/chat-and-notifications/emailhandler/handler"
	"github.com/domesama/chat-and-notifications/emailhandler/service"
	"github.com/domesama/chat-and-notifications/httpserverwrapper"
	"github.com/domesama/doakes/doakeswire"
)

// Injectors from email_handler_di.go:

func StartEmailHandlerContainer() (EmailHandlerContainer, func(), error) {
	resource, err := doakeswire.ProvideResource()
	if err != nil {
		return EmailHandlerContainer{}, nil, err
	}
	metricsConfig := doakeswire.ProvideMetricsConfig()
	telemetryServerConfig, err := doakeswire.ProvideTelemetryServerConfig()
	if err != nil {
		return EmailHandlerContainer{}, nil, err
	}
	options := doakeswire.ProvideServerOptions(resource, metricsConfig, telemetryServerConfig)
	telemetryServer, cleanup, err := doakeswire.ProvideServer(options)
	if err != nil {
		return EmailHandlerContainer{}, nil, err
	}
	httpServerConfig := httpserverwrapper.ProvideHTTPConfig()
	mongoDBConfig := connectionconfig.ProvideMongoDBConfig()
	client, cleanup2, err := connections.ProvideMongoClient(mongoDBConfig)
	if err != nil {
		cleanup()
		return EmailHandlerContainer{}, nil, err
	}
	database := connections.ProvideMongoDatabase(client, mongoDBConfig)
	emailInfoService := service.EmailInfoService{
		DB: database,
	}
	emailConfig := email.ProvideEmailConfig()
	emailSender, cleanup3, err := email.ProvideSMTPEmailSender(emailConfig)
	if err != nil {
		cleanup2()
		cleanup()
		return EmailHandlerContainer{}, nil, err
	}
	chatMailingService := service.ChatMailingService{
		EmailInfoService: emailInfoService,
		EmailConfig:      emailConfig,
		EmailSender:      emailSender,
	}
	purchaseMailingService := service.PurchaseMailingService{
		EmailInfoService: emailInfoService,
		EmailConfig:      emailConfig,
		EmailSender:      emailSender,
	}
	emailHandler := handler.EmailHandler{
		ChatMailingService:     chatMailingService,
		PurchaseMailingService: purchaseMailingService,
	}
	routerCustomizer := handler.ProvideRouterCustomizer(emailHandler)
	httpServer, cleanup4, err := httpserverwrapper.ProvideHTTPServer(httpServerConfig, routerCustomizer)
	if err != nil {
		cleanup3()
		cleanup2()
		cleanup()
		return EmailHandlerContainer{}, nil, err
	}
	emailHandlerContainer := EmailHandlerContainer{
		TelemetryServer: telemetryServer,
		HTTPServer:      httpServer,
	}
	return emailHandlerContainer, func() {
		cleanup4()
		cleanup3()
		cleanup2()
		cleanup()
	}, nil
}
