// Code generated by wireprovider version v1.0.2. DO NOT EDIT.

package wire

import (
	"github.com/google/wire"

	hyhngchatpersistencechangehandler "github.com/domesama/chat-and-notifications/chatpersistencechangehandler"
	zpmevservice "github.com/domesama/chat-and-notifications/chatpersistencechangehandler/service"
)

var ProviderSet = wire.NewSet(
	hyhngchatpersistencechangehandler.ProvideChatPersistenceChangeEventMetric,
	hyhngchatpersistencechangehandler.ProvideChatPersistenceChangeEventStore,
	hyhngchatpersistencechangehandler.ProvideChatPersistenceChangeHandler,
	wire.Struct(new(hyhngchatpersistencechangehandler.ChatPersistenceChangeMessageHandler), "*"),
	wire.Struct(new(zpmevservice.ChatMessageSyncService), "*"),
)

type Locator struct {
	ChatPersistenceChangeEventMetric    hyhngchatpersistencechangehandler.ChatPersistenceChangeEventMetric
	ChatPersistenceChangeEventStore     hyhngchatpersistencechangehandler.ChatPersistenceChangeEventStore
	ChatPersistenceChangeHandler        hyhngchatpersistencechangehandler.ChatPersistenceChangeHandler
	ChatPersistenceChangeMessageHandler *hyhngchatpersistencechangehandler.ChatPersistenceChangeMessageHandler
	ChatMessageSyncService              *zpmevservice.ChatMessageSyncService
}
