// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/wireinject/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wire

import (
	"github.com/domesama/chat-and-notifications/chatpersistencechangehandler"
	"github.com/domesama/chat-and-notifications/chatpersistencechangehandler/config"
	"github.com/domesama/chat-and-notifications/chatpersistencechangehandler/service"
	"github.com/domesama/doakes/doakeswire"
)

// Injectors from chat_persistence_change_handler_di.go:

func StartChatPersistenceChangeHandlerContainer(chatPersistenceChangeHandlerConfig config.ChatPersistenceChangeHandlerConfig) (ChatPersistenceChangeHandlerContainer, func(), error) {
	resource, err := doakeswire.ProvideResource()
	if err != nil {
		return ChatPersistenceChangeHandlerContainer{}, nil, err
	}
	metricsConfig := doakeswire.ProvideMetricsConfig()
	telemetryServerConfig, err := doakeswire.ProvideTelemetryServerConfig()
	if err != nil {
		return ChatPersistenceChangeHandlerContainer{}, nil, err
	}
	options := doakeswire.ProvideServerOptions(resource, metricsConfig, telemetryServerConfig)
	telemetryServer, cleanup, err := doakeswire.ProvideServer(options)
	if err != nil {
		return ChatPersistenceChangeHandlerContainer{}, nil, err
	}
	chatMessageSyncService := service.ChatMessageSyncService{
		Config: chatPersistenceChangeHandlerConfig,
	}
	chatPersistenceChangeMessageHandler := chatpersistencechangehandler.ChatPersistenceChangeMessageHandler{
		ChatMessageSyncService: chatMessageSyncService,
	}
	chatPersistenceChangeEventMetric := chatpersistencechangehandler.ProvideChatPersistenceChangeEventMetric()
	chatPersistenceChangeHandler, cleanup2, err := chatpersistencechangehandler.ProvideChatPersistenceChangeHandler(chatPersistenceChangeHandlerConfig, telemetryServer, chatPersistenceChangeMessageHandler, chatPersistenceChangeEventMetric)
	if err != nil {
		cleanup()
		return ChatPersistenceChangeHandlerContainer{}, nil, err
	}
	chatPersistenceChangeHandlerContainer := ChatPersistenceChangeHandlerContainer{
		TelemetryServer:              telemetryServer,
		ChatPersistenceChangeHandler: chatPersistenceChangeHandler,
	}
	return chatPersistenceChangeHandlerContainer, func() {
		cleanup2()
		cleanup()
	}, nil
}
