// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/wireinject/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wireit

import (
	"github.com/domesama/chat-and-notifications/chatpersistencechangehandler"
	"github.com/domesama/chat-and-notifications/chatpersistencechangehandler/config"
	"github.com/domesama/chat-and-notifications/chatpersistencechangehandler/service"
	"github.com/domesama/chat-and-notifications/cmd/chatpersistencechangehandler/wire"
	"github.com/domesama/chat-and-notifications/connections"
	"github.com/domesama/chat-and-notifications/connections/connectionconfig"
	"github.com/domesama/chat-and-notifications/eventstore"
	"github.com/domesama/doakes/doakeswire"
)

// Injectors from di.go:

func InitChatPersistenceChangeHandlerITTestContainer(chatPersistenceChangeHandlerConfig config.ChatPersistenceChangeHandlerConfig) (ChatPersistenceChangeHandlerITTestContainer, func(), error) {
	resource, err := doakeswire.ProvideResource()
	if err != nil {
		return ChatPersistenceChangeHandlerITTestContainer{}, nil, err
	}
	metricsConfig := doakeswire.ProvideMetricsConfig()
	telemetryServerConfig, err := doakeswire.ProvideTelemetryServerConfig()
	if err != nil {
		return ChatPersistenceChangeHandlerITTestContainer{}, nil, err
	}
	options := doakeswire.ProvideServerOptions(resource, metricsConfig, telemetryServerConfig)
	telemetryServer, cleanup, err := doakeswire.ProvideServer(options)
	if err != nil {
		return ChatPersistenceChangeHandlerITTestContainer{}, nil, err
	}
	chatMessageSyncService := service.ChatMessageSyncService{
		Config: chatPersistenceChangeHandlerConfig,
	}
	chatPersistenceChangeMessageHandler := chatpersistencechangehandler.ChatPersistenceChangeMessageHandler{
		ChatMessageSyncService: chatMessageSyncService,
	}
	chatPersistenceChangeEventMetric := chatpersistencechangehandler.ProvideChatPersistenceChangeEventMetric()
	redisClientConfig := connectionconfig.ProvideRedisClientConfig()
	client, cleanup2, err := connections.ProvideRedisClient(redisClientConfig)
	if err != nil {
		cleanup()
		return ChatPersistenceChangeHandlerITTestContainer{}, nil, err
	}
	redisEventStoreConfig := eventstore.ProvideRedisEventStoreConfig()
	chatPersistenceChangeEventStore := chatpersistencechangehandler.ProvideChatPersistenceChangeEventStore(client, redisEventStoreConfig)
	chatPersistenceChangeHandler, cleanup3, err := chatpersistencechangehandler.ProvideChatPersistenceChangeHandler(chatPersistenceChangeHandlerConfig, telemetryServer, chatPersistenceChangeMessageHandler, chatPersistenceChangeEventMetric, chatPersistenceChangeEventStore)
	if err != nil {
		cleanup2()
		cleanup()
		return ChatPersistenceChangeHandlerITTestContainer{}, nil, err
	}
	chatPersistenceChangeHandlerContainer := wire.ChatPersistenceChangeHandlerContainer{
		TelemetryServer:              telemetryServer,
		ChatPersistenceChangeHandler: chatPersistenceChangeHandler,
	}
	chatpersistencechangehandlerChatPersistenceChangeMessageHandler := &chatpersistencechangehandler.ChatPersistenceChangeMessageHandler{
		ChatMessageSyncService: chatMessageSyncService,
	}
	serviceChatMessageSyncService := &service.ChatMessageSyncService{
		Config: chatPersistenceChangeHandlerConfig,
	}
	locator := wire.Locator{
		ChatPersistenceChangeEventMetric:    chatPersistenceChangeEventMetric,
		ChatPersistenceChangeEventStore:     chatPersistenceChangeEventStore,
		ChatPersistenceChangeHandler:        chatPersistenceChangeHandler,
		ChatPersistenceChangeMessageHandler: chatpersistencechangehandlerChatPersistenceChangeMessageHandler,
		ChatMessageSyncService:              serviceChatMessageSyncService,
	}
	chatPersistenceChangeHandlerITTestContainer := ChatPersistenceChangeHandlerITTestContainer{
		ChatPersistenceChangeHandlerContainer: chatPersistenceChangeHandlerContainer,
		Locator:                               locator,
		RedisClient:                           client,
	}
	return chatPersistenceChangeHandlerITTestContainer, func() {
		cleanup3()
		cleanup2()
		cleanup()
	}, nil
}
