// Code generated by wireprovider version v1.0.2. DO NOT EDIT.

package wire

import (
	"github.com/google/wire"

	cykpkhandler "github.com/domesama/chat-and-notifications/chatwebsocketshandler/handler"
	cykpkservice "github.com/domesama/chat-and-notifications/chatwebsocketshandler/service"
	hyhnghttpserverwrapper "github.com/domesama/chat-and-notifications/httpserverwrapper"
)

var ProviderSet = wire.NewSet(
	wire.Struct(new(cykpkhandler.ChatWebSocketHandler), "*"),
	cykpkhandler.ProvideRouterCustomizer,
	wire.Struct(new(cykpkservice.ChatPersistenceService), "*"),
)

type Locator struct {
	ChatWebSocketHandler   *cykpkhandler.ChatWebSocketHandler
	RouterCustomizer       hyhnghttpserverwrapper.RouterWithWebSocketCustomizer
	ChatPersistenceService *cykpkservice.ChatPersistenceService
}
