// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wireit

import (
	"github.com/domesama/chat-and-notifications/cmd/emailhandler/wire"
	"github.com/domesama/chat-and-notifications/connections"
	"github.com/domesama/chat-and-notifications/connections/connectionconfig"
	"github.com/domesama/chat-and-notifications/email"
	"github.com/domesama/chat-and-notifications/emailhandler/handler"
	"github.com/domesama/chat-and-notifications/emailhandler/service"
	"github.com/domesama/chat-and-notifications/httpserverwrapper"
	"github.com/domesama/chat-and-notifications/ittest/ittesthelper"
	"github.com/domesama/doakes/doakeswire"
)

// Injectors from di.go:

func InitEmailHandlerITTestContainer() (EmailHandlerITTestContainer, func(), error) {
	mongoDBConfig := connectionconfig.ProvideMongoDBConfig()
	client, cleanup, err := connections.ProvideMongoClient(mongoDBConfig)
	if err != nil {
		return EmailHandlerITTestContainer{}, nil, err
	}
	database := connections.ProvideMongoDatabase(client, mongoDBConfig)
	emailInfoService := service.EmailInfoService{
		DB: database,
	}
	emailConfig := email.ProvideEmailConfig()
	simpleEmailSender := ittesthelper.ProvideSimpleEmailSender()
	chatMailingService := service.ChatMailingService{
		EmailInfoService: emailInfoService,
		EmailConfig:      emailConfig,
		EmailSender:      simpleEmailSender,
	}
	purchaseMailingService := service.PurchaseMailingService{
		EmailInfoService: emailInfoService,
		EmailConfig:      emailConfig,
		EmailSender:      simpleEmailSender,
	}
	emailHandler := &handler.EmailHandler{
		ChatMailingService:     chatMailingService,
		PurchaseMailingService: purchaseMailingService,
	}
	handlerEmailHandler := handler.EmailHandler{
		ChatMailingService:     chatMailingService,
		PurchaseMailingService: purchaseMailingService,
	}
	routerCustomizer := handler.ProvideRouterCustomizer(handlerEmailHandler)
	serviceChatMailingService := &service.ChatMailingService{
		EmailInfoService: emailInfoService,
		EmailConfig:      emailConfig,
		EmailSender:      simpleEmailSender,
	}
	serviceEmailInfoService := &service.EmailInfoService{
		DB: database,
	}
	servicePurchaseMailingService := &service.PurchaseMailingService{
		EmailInfoService: emailInfoService,
		EmailConfig:      emailConfig,
		EmailSender:      simpleEmailSender,
	}
	locator := wire.Locator{
		EmailHandler:           emailHandler,
		RouterCustomizer:       routerCustomizer,
		ChatMailingService:     serviceChatMailingService,
		EmailInfoService:       serviceEmailInfoService,
		PurchaseMailingService: servicePurchaseMailingService,
	}
	resource, err := doakeswire.ProvideResource()
	if err != nil {
		cleanup()
		return EmailHandlerITTestContainer{}, nil, err
	}
	metricsConfig := doakeswire.ProvideMetricsConfig()
	telemetryServerConfig, err := doakeswire.ProvideTelemetryServerConfig()
	if err != nil {
		cleanup()
		return EmailHandlerITTestContainer{}, nil, err
	}
	options := doakeswire.ProvideServerOptions(resource, metricsConfig, telemetryServerConfig)
	telemetryServer, cleanup2, err := doakeswire.ProvideServer(options)
	if err != nil {
		cleanup()
		return EmailHandlerITTestContainer{}, nil, err
	}
	httpServerConfig := httpserverwrapper.ProvideHTTPConfig()
	httpServer, cleanup3, err := httpserverwrapper.ProvideHTTPServer(httpServerConfig, routerCustomizer)
	if err != nil {
		cleanup2()
		cleanup()
		return EmailHandlerITTestContainer{}, nil, err
	}
	emailHandlerContainer := wire.EmailHandlerContainer{
		TelemetryServer: telemetryServer,
		HTTPServer:      httpServer,
	}
	emailHandlerITTestContainer := EmailHandlerITTestContainer{
		Locator:               locator,
		EmailHandlerContainer: emailHandlerContainer,
		Database:              database,
		SimpleEmailSender:     simpleEmailSender,
	}
	return emailHandlerITTestContainer, func() {
		cleanup3()
		cleanup2()
		cleanup()
	}, nil
}
